
advertised.listeners=INTERNAL://broker1:9092,CLIENT://broker1:9094,TOKEN://broker1:9095

allow.everyone.if.no.acl.found=false

authorizer.class.name=io.confluent.kafka.security.authorizer.ConfluentServerAuthorizer

auto.create.topics.enable=false

confluent.authorizer.access.rule.providers=CONFLUENT,KRAFT_ACL

confluent.balancer.enable=false

confluent.balancer.topic.replication.factor=2

confluent.cluster.link.metadata.topic.replication.factor=2

confluent.license.topic.replication.factor=2

confluent.metadata.server.advertised.listeners=https://broker1:8091

confluent.metadata.server.authentication.method=BEARER

confluent.metadata.server.listeners=https://0.0.0.0:8091

confluent.metadata.server.ssl.key.password=changeit

confluent.metadata.server.ssl.keystore.location=/etc/kafka/secrets/server.keystore.p12

confluent.metadata.server.ssl.keystore.password=changeit

confluent.metadata.server.ssl.keystore.type=PKCS12

confluent.metadata.server.ssl.truststore.location=/etc/kafka/secrets/truststore.p12

confluent.metadata.server.ssl.truststore.password=changeit

confluent.metadata.server.ssl.truststore.type=PKCS12

confluent.metadata.server.token.key.path=/etc/kafka/secrets/keypair.pem

confluent.metadata.server.token.max.lifetime.ms=3600000

confluent.metadata.server.token.signature.algorithm=RS256

confluent.metadata.topic.replication.factor=2

confluent.reporters.telemetry.auto.enable=false

confluent.security.event.logger.exporter.kafka.topic.replicas=2

controller.listener.names=CONTROLLER

controller.quorum.voters=1@controller1:9093

default.replication.factor=2

inter.broker.listener.name=INTERNAL

ldap.com.sun.jndi.ldap.read.timeout=3000

ldap.group.member.attribute=member

ldap.group.member.attribute.pattern=uid=(.*),ou=users,dc=corp,dc=demo

ldap.group.name.attribute=cn

ldap.group.object.class=groupOfNames

ldap.group.search.base=ou=groups,dc=corp,dc=demo

ldap.java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory

ldap.java.naming.provider.url=ldap://openldap:389

ldap.java.naming.security.authentication=simple

ldap.java.naming.security.credentials=ldap-bind-pw

ldap.java.naming.security.principal=cn=svc-kafka-ldap,ou=system,dc=corp,dc=demo

ldap.refresh.interval.ms=5000

ldap.search.mode=GROUPS

ldap.user.name.attribute=uid

ldap.user.object.class=inetOrgPerson

ldap.user.search.base=ou=users,dc=corp,dc=demo

listener.name.client.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required;

listener.name.client.plain.sasl.server.callback.handler.class=io.confluent.security.auth.provider.ldap.LdapAuthenticateCallbackHandler

listener.name.client.sasl.enabled.mechanisms=PLAIN,SCRAM-SHA-512

listener.name.client.scram_sha_512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;

listener.name.controller.plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka-broker" password="broker-secret";

listener.name.controller.sasl.enabled.mechanisms=PLAIN

listener.name.internal.sasl.enabled.mechanisms=SCRAM-SHA-512

listener.name.internal.scram_sha_512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-broker" password="broker-secret";

listener.name.token.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required publicKeyPath="/etc/kafka/secrets/public.pem";

listener.name.token.oauthbearer.sasl.login.callback.handler.class=io.confluent.kafka.server.plugins.auth.token.TokenBearerServerLoginCallbackHandler

listener.name.token.oauthbearer.sasl.server.callback.handler.class=io.confluent.kafka.server.plugins.auth.token.TokenBearerValidatorCallbackHandler

listener.name.token.sasl.enabled.mechanisms=OAUTHBEARER

listener.security.protocol.map=CONTROLLER:SASL_SSL,INTERNAL:SASL_SSL,CLIENT:SASL_SSL,TOKEN:SASL_SSL

listeners=INTERNAL://broker1:9092,CLIENT://0.0.0.0:9094,TOKEN://broker1:9095

log.dirs=/var/lib/kafka/data

node.id=11

offsets.topic.replication.factor=2

password.encoder.secret=encoder-secret

process.roles=broker

sasl.mechanism.controller.protocol=PLAIN

sasl.mechanism.inter.broker.protocol=SCRAM-SHA-512

ssl.client.auth=none

ssl.endpoint.identification.algorithm=https

ssl.key.credentials=sslkey_creds

ssl.key.password=changeit

ssl.keystore.credentials=keystore_creds

ssl.keystore.filename=server.keystore.p12

ssl.keystore.location=/etc/kafka/secrets/server.keystore.p12

ssl.keystore.password=changeit

ssl.keystore.type=PKCS12

ssl.truststore.location=/etc/kafka/secrets/truststore.p12

ssl.truststore.password=changeit

ssl.truststore.type=PKCS12

super.users=User:kafka-broker;User:kafka-controller;User:bootstrap;User:gary

transaction.state.log.min.isr=1

transaction.state.log.replication.factor=2
